services:
    zookeeper:
        image: wurstmeister/zookeeper:latest
        container_name: zookeeper
        ports:
            - "2181:2181"

    kafka:
        image: wurstmeister/kafka:latest
        container_name: kafka
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        expose:
            - "9093"
        environment:
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "ecommerce-orders:1:1"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    mongo:
        image: mongodb/mongodb-community-server:latest
        container_name: mongo
        ports:
            - "27017:27017"

    spark-master:
        build: ./docker/spark-master
        image: spark-master:4.0
        container_name: spark-master
        ports:
            - "9090:8080" # Spark Master UI
            - "7077:7077" # Spark Master port
        volumes:
            - ./notebooks:/opt/spark/work-dir/notebooks
            - ./src:/opt/spark/work-dir/src
        environment:
            - SPARK_LOCAL_IP=spark-master
            - PYTHONPATH=/opt/spark/work-dir/src

    spark-worker:
        build: ./docker/spark-worker
        image: spark-worker:4.0
        container_name: spark-worker
        depends_on:
            - spark-master
        environment:
            - PYTHONPATH=/opt/spark/work-dir/src
            - SPARK_DRIVER_MEMORY=128m
            - SPARK_EXECUTOR_MEMORY=256m
            - SPARK_MASTER=spark://spark-master:7077
            - SPARK_WORKER_CORES=1
            - SPARK_WORKER_MEMORY=1G
        volumes:
            - ./notebooks:/opt/spark/work-dir/notebooks
            - ./src:/opt/spark/work-dir/src

    spark-notebook:
        image: spark-base:4.0
        container_name: spark-notebook
        command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''
        depends_on:
            - spark-worker
        environment:
            - PYTHONPATH=/opt/spark/work-dir/src
        ports:
            - "8888:8888"
            - "4040:4040" # Spark App UI (active while a job runs)
        env_file:
            - .env
        volumes:
            - ./notebooks:/opt/spark/work-dir/notebooks
            - ./src:/opt/spark/work-dir/src
